name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build on Java ${{ matrix.java }} for ${{ matrix.plaform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 15
        platform: 
          - macos-latest
          - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Test
        run: |
          ./gradlew -i test
